function change_warnings(enable)
%CHANGE_WARNINGS enables or disables move/depreciation warnings
%
% CHANGE_WARNINGS 'on' or CHANGE_WARNINGS('on') enables warnings.
%
% CHANGE_WARNINGS 'off' or CHANGE_WARNINGS('off') disables warnings.
%
% This file is part of the optical tweezers toolbox.
% See LICENSE.md for information about using/distributing this file.

% Check number of inputs
if nargin == 0
  error('ott:change_warnings:no_input', ...
      'change_warnings expects input: on or off to enable/disable warnings');
end

% Check input is on or off
if ~strcmpi(enable, 'on') && ~strcmpi(enable, 'off')
  error('ott:change_warnings:input_value', ...
      'change_warnings expects input to be either on or off');
end

% List of warnings we control
warnings = { 'ott:angulargrid:move', ...
    'ott:axisym_boundarypoints:move', ...
    'ott:combined_index:move', ...
    'ott:hermite:move', ...
    'ott:hgmode:move', ...
    'ott:incecoefficients:move', ...
    'ott:iseven:move', ...
    'ott:isodd:move', ...
    'ott:ka2nmax:move', ...
    'ott:laguerre:move', ...
    'ott:legendrerow:move', ...
    'ott:lgmode:move', ...
    'ott:lg_mode_w0:move', ...
    'ott:matchsize:move', ...
    'ott:nmax2ka:move', ...
    'ott:paraxial_transformation_matrix:move', ...
    'ott:perpcomponent:move', ...
    'ott:rotation_matrix:move', ...
    'ott:rtp2xyz:move', ...
    'ott:rtpv2xyzv:move', ...
    'ott:sbesselh1:move', ...
    'ott:sbesselh2:move', ...
    'ott:sbesselh:move', ...
    'ott:sbesselj:move', ...
    'ott:shapesurface:move', ...
    'ott:spharm:move', ...
    'ott:threewide:move', ...
    'ott:translate_z:move', ...
    'ott:vsh:move', ...
    'ott:vswfcart:move', ...
    'ott:vswf:move', ...
    'ott:wigner_rotation_matrix:move', ...
    'ott:xyz2rtp:move', ...
    'ott:xyzv2rtpv:move' };

% Turn off warnings
for ii = 1:length(warnings)
  warning(enable, warnings{ii});
end
